### ISSUE TITLE
Esphomelib

### ISSUE THREAD

**Issue by PhoenixMage** [SwiCago/HeatPump#102]
Hi all,

Has anyone considered integrating this into esphomelib? Built-in integration with home assistant, OTA updates, ++

https://esphomelib.com/index.html

Sadly in 44°c temps I don't have a Mitsubishi unit yet but should be happening in the near future.

If no one has integrated by then I am happy to take a stab myself.

**Comment by SwiCago** [comment]
@PhoenixMage please ask in our gitter chat. Maybe someone has. I have not, as I use my own custom automation with VPN. I can't stand anything that needs the cloud. 

Link to gitter chat https://gitter.im/Mitsubishi-Heat-Pump?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

If no one has made an integration, then your attempt will be an appreciated addition. Thanks
