### ISSUE TITLE
Hassio Pull request

### ISSUE THREAD

**Issue by naldoxable** [SwiCago/HeatPump#108]
Can you create a **pull request** to integrate it on [Home Assistant](https://github.com/home-assistant/home-assistant) repository?
It would be nice if it will be part of tested components!

**Comment by SwiCago** [comment]
I do not maintain integrations. They were implemented by others and are not part of the library, but rather as examples of how you can use the library. I will not maintain them. I suggest joining the gitter chat and ask those who did create the integration resolve any issues.
