### ISSUE TITLE
The "wideVane" set does not work

### ISSUE THREAD

**Issue by fer8sp** [SwiCago/HeatPump#121]
There is an error in the library (HeatPump.cpp).

Original:
```
void HeatPump::setWideVaneSetting(const char* setting) {
  int index = lookupByteMapIndex(WIDEVANE_MAP, 7, setting);
  if (index > -1) {
    wantedSettings.wideVane = VANE_MAP[index];
  } else {
    wantedSettings.wideVane = VANE_MAP[0];
  }
}
```

Must be:
```
void HeatPump::setWideVaneSetting(const char* setting) {
  int index = lookupByteMapIndex(WIDEVANE_MAP, 7, setting);
  if (index > -1) {
    wantedSettings.wideVane = WIDEVANE_MAP[index];
  } else {
    wantedSettings.wideVane = WIDEVANE_MAP[0];
  }
}
```

I thought he drove me crazy. In addition, my unit (MSZ-AP35) sends different values {0x81, 0x82, 0x83, 0x84, 0x85, 0x88, 0x8c} for widevane.  I am solved !!!

Thanks for the great job

**Comment by SwiCago** [comment]
Thanks, someone broke that after converting stings to char* ... they said they tested and a second person confirmed it. I guess they missed that one. I'll update it right away
