### ISSUE TITLE
SoftwareSerial for Connection

### ISSUE THREAD

**Issue by sfozz** [SwiCago/HeatPump#136]
Just been trying this library out... most awesome!

I'm curious is there a specific reason for not supporting the SoftwareSerial library for the connection to the heatpump?

**Comment by SwiCago** [comment]
It has to be recoded differently in  order for soft serial to work right...with a specific library(CustomSoftSerial). Standard soft serial does not work. I made a working version for someone needing it for an uno. Join gitter chat and scroll up about 2 months and you'll find the discussion. But to get you started http://www.swicago.com/HeatPumpSoftSerial.zip
Have fun
