### ISSUE TITLE
Entity no more available

### ISSUE THREAD

**Issue by simox83971** [SwiCago/HeatPump#145]
With the last release of HA 0.101.1 the integration no longer works.
On the overview tab I saw the error message "Entity not available: climate.room_heatpump".
Some help?
<img width="1046" alt="Home_Assistant" src="https://user-images.githubusercontent.com/30441426/67991997-69cfb200-fc3b-11e9-9e82-e1eabd745fe1.png">

**Comment by SwiCago** [comment]
#138
