### ISSUE TITLE
MHK1 integration

### ISSUE THREAD

**Issue by reardencode** [SwiCago/HeatPump#146]
Not sure if others would be interested in this, but I'd be interested in enabling the same functionality that Mitsubishi's WiFi interface V2 does where the MHK1 receiver can connect through the WiFi interface and still control the system to some degree.

If there's interest, I'll be working on integrating this functionality into a new US PEAD HeatPump over the next 3-6 months and can make a PR. (Otherwise I'll just hack something together to meet my needs)

**Comment by SwiCago** [comment]
It would probably be best if you make your mhk1 idea a library of it's own and provide an example ino that uses both libraries together.
