### ISSUE TITLE
strcat() appending to a constant

### ISSUE THREAD

**Issue by RyanDhuse** [SwiCago/HeatPump#149]
https://github.com/SwiCago/HeatPump/blob/c87ff9f05c97e4de3e6438dead76798cbef80de7/examples/mitsubishi_heatpump_mqtt_esp8266_esp32/mitsubishi_heatpump_mqtt_esp8266_esp32.ino#L248

`mqtt_client.publish(heatpump_debug_topic, strcat("heatpump: wrong mqtt topic: ", topic));`

Using strcat this way is going to cause a SIGSEGV.  The first parameter can't be constant because it's used as the destination buffer.

**Comment by SwiCago** [comment]
@RyanDhuse I am not the author of this example, so I do not know if it is correct or not. I have also not heard of anyone getting SIGSEGV. Have you tried to cause it with this example? If so and it does in fact cause a problem, then please suggest a fix or better yet make a pull.
Thanks

**Comment by SwiCago** [comment]
Strcat removed. The else in thoery should never be called if subscribe is done right
