### ISSUE TITLE
Hardware. Pre-made cable

### ISSUE THREAD

**Issue by alexmc1510** [SwiCago/HeatPump#150]
Hello all,

I am one of your followers. I have just installed 3 units of MSZ-HR and I want to include them in my Hassio system thanks to this software. The problem I have found is that in Europe I am not able to find the premade cables for CN105. I know I can do it and I have located the parts but I would like to make it well. I would like to know if someone has found this cables in Europe or if someone could sell them through ebay or other method. I am from Spain.

Thanks in advance.

**Comment by SwiCago** [comment]
This is not an issue with the library. Ask these kind of questions in gitter chat!
