### ISSUE TITLE
CN105 female cable

### ISSUE THREAD

**Issue by TungstenE2** [SwiCago/HeatPump#160]
Hi all,

according to the parts list a JST PA 5-pin 2.0mm female connector is needed.

As I do not find JST **PA** but JST **PH** I was wondering if this is the same or what is the difference.

https://www.ebay.de/itm/JST-PH-2-0mm-Stecker-Buchse-26AWG-Kabel-30cm-Connector-2-10-Pin-2-0mm/183607216953

Or can somebody provide me with a JST PA ebay link shipping to Germany?

Thx

**Comment by SwiCago** [comment]
No clue, but this question is not an issue! Use gitter chat link at top corner of this library for general questions.
