### ISSUE TITLE
Powerful mode not a macro for this unit, but a separate fan speed

### ISSUE THREAD

**Issue by melyux** [SwiCago/HeatPump#161]
I saw in the chat that the Powerful mode on the remote is just a macro (top fan speed and horizontal vane all the way down). For our unit, the powerful mode indeed puts the vanes down all the way, but the fan speed is louder and more, well, powerful than the full speed fan (speed 4).

**Comment by SwiCago** [comment]
Finding a new hidden function is not an issue. Use chat or #39 for that.
