### ISSUE TITLE
WemosD1 and remote control

### ISSUE THREAD

**Issue by skorc99** [SwiCago/HeatPump#163]
Hello,
i have strange issue.MSZ-25
Turn ON with remote - AC turns off after 20s
Turn ON with wemos and use remote after that
all works- temp, mode, fan..

I cut rx/tx pin.
Any idea?
U

**Comment by SwiCago** [comment]
@skorc99 not a bug. You are using an external source to update the HP. The controller is overriding settings that we given to it to pass to HP. If you want to allow external remote to also control hp settings of the controller, use hp.enableExternalUpdate()
