### ISSUE TITLE
Elegoo Mega 2560 R3 with MSZ-AP25VG-E1

### ISSUE THREAD

**Issue by gfreccia** [SwiCago/HeatPump#177]
Hi All,

I've adapted the code for Elegoo Mega 2560 R3 with Ethernet Shield to control MSZ-AP25VG-E1 (I assume the unit is compatible). 
The IP/MQTT side works properly but I don't see communication with the pump.
I assume that the code uses UART1; or do I've to set something to select the serial port?

Thank you!

**Comment by SwiCago** [comment]
The  MSX-AP25VG has been reported working in #13 
As for how to make your board of choice work with the library is not a bug or issue with the library, but rather a user issue. Please ask your question(s) in the chat, linked on the main mage of this library.
