### ISSUE TITLE
Is there a way to make the air conditioner use an external temperature sensor?

### ISSUE THREAD

**Issue by amayii0** [SwiCago/HeatPump#183]
(moving out of other topic) 

Is there a way to make the air conditioner use an external temperature sensor?

_Originally posted by @AntoxaSa in https://github.com/SwiCago/HeatPump/issues/13#issuecomment-1233136907_

**Comment by fastbike** [comment]
It depends on your system. If there's no direct connection, then use an external sensor with a control system like Home Assistant. That will be a separate node.
My unit has a sensor built into the indoor unit, and another on a wired control panel in the same room. I find the control panel one to be accurate enough.

**Comment by AntoxaSa** [comment]
I use the home assistant, the thermostat is automatically thrown from the air conditioner there. The sensor prokidyvaetsya internal air conditioner. And how to use an external temperature sensor for example akara?

**Comment by jb123567** [comment]
I'm using this library in ESPHome which within Home Assistant allows you to use data from an external sensor to override the internal thermostat.

**Comment by AntoxaSa** [comment]
> I'm using this library in ESPHome which within Home Assistant allows you to use data from an external sensor to override the internal thermostat.
is there an example implementation through esphome?

**Comment by SwiCago** [comment]
yes, use command setRemoteTemperature(float TempInC)
