### ISSUE TITLE
What kind of connector

### ISSUE THREAD

**Issue by Manhem** [SwiCago/HeatPump#193]
Hi.
Does anyone know what kind of connector we find on the WiFi module and where to find it?
Maybe Digikey part number.
I don't want to dismount my air heatpump, still warranty on it.
It has been much easier just to replace the WiFi module with my "own".
No need to distroy something and I can put the new one in the same place as the old WiFi module.

(gitter chat not working (error 404)

**Comment by fastbike** [comment]
Did you read https://chrdavis.github.io/hacking-a-mitsubishi-heat-pump-Part-1/

**Comment by brgaulin** [comment]
From the readme, there is a link to the digikey website here: https://github.com/SwiCago/HeatPump/blob/master/README.md?plain=1#L138

From there, the datasheet has alternative connectors if you want a different kind. I am in the middle of trying this out myself, and went with `PALR-05VF` + `APALPAL22K305`. That should enable me to make an "extension cable" that interfaces with the cable going to my existing kumo device. The wires will then get soldered directly into my ESP8266 with strain relief on a 3d printed box.

If you want the solderable connectors, the datasheet on digikey shows many options. I think the one you would want to match the kumo devices is a `S05B-PASK-2`

**Comment by Manhem** [comment]
That connector is for the CN105 connector.
I would like to have that one you can find in the WiFi module and that is not the same.

**Comment by brgaulin** [comment]
The CN105 is the most common type. If you don't have that one, can you share what you are trying to mimic? Pictures or model numbers would help. I only know the CN105, but hopefully someone else can help with that extra context.

**Comment by Manhem** [comment]
The module I will connect to is a WiFi interface, model: MAC-577IF2E.
Here are some pictures. 
I apologize for the poor quality of one of the pictures.
So here you can see what kind of connecter I like to have.

![_vyr_479_Mitsubishi-Wi-Fi-1551770532](https://user-images.githubusercontent.com/76493147/234481509-c649d507-0756-4a63-8b7c-357d2e03c629.jpg)
![IMG_1621](https://user-images.githubusercontent.com/76493147/234480472-019d193e-b9f4-49fb-abd1-7b8bac60d29d.JPG)
![IMG_1623](https://user-images.githubusercontent.com/76493147/234480491-5909c4ad-ee3c-4f8d-94e0-a28b293efb52.JPG)
![IMG_1624](https://user-images.githubusercontent.com/76493147/234480500-916b04ce-8c73-4fcf-9a0a-778cf01198f2.JPG)

**Comment by brepdcom** [comment]
If you can measure the pin pitch, you can narrow down the possibilities significantly.  Start looking at JST's Wire-to-Board connectors with the pitch known and the part in hand, and you can probably figure out the specification.  
https://www.jst.com/products/crimp-style-connectors-wire-to-board-type/

**Comment by Igor-Yavych** [comment]
You won't damage warranty because parts you need to remove to install it are mostly the same parts you need to remove for installation of the unit itself

**Comment by SwiCago** [comment]
Chat link is fixed https://app.gitter.im/#/room/#Mitsubishi-Heat-Pump_Lobby:gitter.im
This question is beyond the scope of this library. Please ask in chat if anyone can help source parts
