### ISSUE TITLE
serial connection problem

### ISSUE THREAD

**Issue by Gia79** [SwiCago/HeatPump#201]
![Immagine 2023-08-29 185044](https://github.com/SwiCago/HeatPump/assets/134832033/6bfc1640-f7ce-4203-888a-fbc06997076d)
hello, I'm trying the ali kamali emulator, but the serial communication gives me errors. Could you help me figure out what could be the problem? I set the pc com port with baud rate 2400 - 1 bit stop - even parity and I flashed an esp01 with your firmware Hpcontrol8266.

**Comment by SwiCago** [comment]
not familiar kamali, try asking for help in chat. make sure your emulator naturalization pulls tx and rx high when inactive. the emulator must also respond with correct packets otherwise esp01 will never think it is connected. good luck
