### ISSUE TITLE
Fan speed 4 issue - compressor frequency

### ISSUE THREAD

**Issue by tommaso-ascani** [SwiCago/HeatPump#203]
I have problem with the fan speed 4: it doesn't work, if i set fan speed to 4 or 3 nothing happen.
So after understand how read the packet, i saw that when i set fan speed 4 from the remote control (mitsubishi controller) the packet doesn't change.

{"packetRecv":"fc 62 01 30 10 02 00 00 01 03 07 05 00 00 00 03 00 00 00 00 00 48 "}

This is the packet that remains the same when i set fan speed to 4 or 3.
I tried to send diffent fan speed byte but nothing.
So the machine doesn't tell nothing about the value of fan speed byte, but also trying every value from 0x00 to 0x0f solved my problem.

The only info packet that change when i set fan speed from 3 to 4, is the compressor frequency vaue as follow:

{"packetRecv":"fc 62 01 30 10 06 00 00 04 01 00 00 00 00 00 00 00 00 00 00 00 52 "}
{"packetRecv":"fc 62 01 30 10 06 00 00 06 01 00 00 00 00 00 00 00 00 00 00 00 50 "}

But i don't know how to change compressor frequency with a set packet (classic "fc 41 ...").

Do someone know how to do it?

**Comment by SwiCago** [comment]
conpressor frequency is read only. it goes up and down depending on amount of power needed to fulfill the desired settings.
As for fan speeds, wall units generally support 4, attic units 3. this library does not differentiate between units. not all commands are supported by all units.
you may have to enable debugging and watch for changed packets. if you believe 4 speeds are supported, it may be a different packet on your unit. sitch between fan speeds 1, 2,3,4 and you should see somewhere a packet increment. maybe you unit only supports 3 speeds and the remote lies.
