### ISSUE TITLE
Wide Vane mode Auto

### ISSUE THREAD

**Issue by DirkMu** [SwiCago/HeatPump#205]
My units MSZ- LN support wide vane mode AUTO. This can also be controlled via MelCloud. Thus I assume it is also exposed via CN105. Can this be added?

**Comment by SwiCago** [comment]
You would need to enable DEBUG packet mode and watch what packet changes when using the remote. Once you find out what packet changes and what the values correspond to, you can use the custom packet send to confirm that you got it right. Then once confirmed, you can modify the code for you unit and if you do it right, where a compile flag can be set, then you could issue a pull request.
But as for me doing the work for you, that won't happen, as I do not have that unit. If you are not familiar with coding, then I suggest going to the chat (link on main page) and ask for help there. Maybe some has same unit and has already got a work around. Good luck
