### ISSUE TITLE
Very slow reponse

### ISSUE THREAD

**Issue by fastbike** [SwiCago/HeatPump#218]
I'm finding my connection to the heatpump very slow.

I have set the IP to 192.168.042.  I can see this has been assigned a DHCP lease by my router and the device is online.

Browsing to this address eventually shows the menu (it took over a minute), clicking the "Control" item results in a time out.

Where do i start in diagnosing / fixing this ?

**Comment by SwiCago** [comment]
That is outside the scope of this project library. Try an ESP specific forum. Maybe start with a simple web project and then work your way to this library.
