### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by JamesDAdams** [SwiCago/HeatPump#223]
Hi,

i plug my esp to my heatPump but only the uptime work...

any idea ?

![image](https://github.com/user-attachments/assets/a1b38522-7c7d-474f-af9c-ed880102aa5a)
![image](https://github.com/user-attachments/assets/3974f41e-d979-46eb-bc58-c75c46ea1082)
![image](https://github.com/user-attachments/assets/9e7c2a33-3957-45ca-a21e-dbc07d740164)
![image](https://github.com/user-attachments/assets/eda646d6-1406-461b-93ea-5d202ea00128)
![image](https://github.com/user-attachments/assets/2e9c3c52-0245-4daf-b7a7-884f994c4bb6)
![image](https://github.com/user-attachments/assets/6d594f1f-d970-483c-ab9c-faca1ce0e3b1)

**Comment by SwiCago** [comment]
USe debug mode and look at the packets. If the initial packet to enable external control is sent over and over, then you have might not be receiving data back. To test if you are not getting data back, after init packet, send an ON command. If unit turns on, then your TX is fine and your RX is not. If the unit does not turn on, then your TX is bad. You may need a pullup resistor on one or both.

**Comment by apppie123** [comment]
You've plugged it into an Ecodan.. Swicago is not compatible with AirToWater pumps.
