### ISSUE TITLE
MQTT with multiple HeatPumps

### ISSUE THREAD

**Issue by SwiCago** [SwiCago/HeatPump#37]
@kayno, how do you send a command to one specific client?
I have 6 zones and if I send heatpump/set as per your sketch it turns them all on.
Do we need to change the topic to be "/heatpump/clientid/set" ?

**Comment by kayno** [comment]
@SwiCago yeah, you'd just have a different topic for each heatpump. my personal setup is by room, as follows:

```
home/living-area/heatpump
home/living-area/heatpump/set
```

I have lots of other topics all in this structure, e.g.

```
home/living-area/blind
home/bedroom/blind
home/study/temperature
home/study/light
````

**Comment by SwiCago** [comment]
@kayno Thanks, that is what i thought.
