### ISSUE TITLE
Any luck with older units?

### ISSUE THREAD

**Issue by pnuding** [SwiCago/HeatPump#49]
Did anyone investigate older units that don't have the famous CN105 connector? I was reading that it's alternatively called CN92 on some of the in-ceiling and ducted systems. However the older models (without Inverter) don't have either of these connectors. 

I was looking at a PEAD-RP2.5GA ducted unit and it's got a CN90 "Wireless" port meant for IR remote control receivers as well as a connector CN51 called "HA Terminal-A" whose purpose I don't understand. However I've not found a clear output signal, but I wasn't able to check the unit in place while running, just the indoor board on its own, so it might just not have output anything :/

Here's the pins I've been able to identify:

CN90 Wireless
Pin 1: goes to IO pin 20 of the CPU via a 200Ohm resistor, and has a 22k pullup
Pin 2: goes to IO pin 21 of the CPU via a 200Ohm resistor, and has a 22k pullup
Pin 3: GND
Pin 4: not sure 
Pin 5: 5V
Pin 6: driven against GND via a NPN transistor (Q71) from IO pin 18 on the CPU
Pin 7: driven against GND via a NPN transistor (Q71) from IO pin 18 on the CPU
Pin 8: not sure
Pin 9: 12-15V unregulated

CN51 HA Terminal-A
Pin 1+3: 12-15V unregulated
Pin 2+4: not sure

**Comment by SwiCago** [comment]
Hi, I highly doubt the protocol for either port is identical to cn105. 
CN51 is a relay adapter, so you can't use that for controlling the unit. I believe it is used for monitoring
https://www.mitsubishi-aircon.com.ua/restricted/Manuals/WT02522X02.pdf
CN90 looks like a dual purpose port. I bet pins 6 and 7 are to drive some indicator lamps on the accessory and pins 1 and 2 are for RX/TX. But I highly doubt the protocol is identical. If anything it would be identical to IR protocol others have reverse engineered. 
https://github.com/r45635/HVAC-IR-Control/blob/master/Protocol/Mitsubishi_IR_Packet_Data_v1.1-FULL.pdf

But again, without connecting a logic analyzer to it with a controller attached, there is no way of knowing.
