### ISSUE TITLE
Can you use Wemos D1 or NodeMCU?

### ISSUE THREAD

**Issue by xbmcnut** [SwiCago/HeatPump#61]
Hi there,

Great work on this one. I just bought a house with 4 x Mitsi heat pumps and I use Home Assistant now so quite fizzed when I discovered your repo! Here's hoping the inverters are the right model. Instead of using a 01 chipset, could you use one of the above boards to negate the use of the 5v reg? Would you still need the 10k pullups on the Tx and Rx lines?

**Comment by schotime** [comment]
I use the 5v nanos straight in.

**Comment by xbmcnut** [comment]
Arduino nano? They have no WiFi. Bit confused.

**Comment by xbmcnut** [comment]
I see others are using nodemcu so I'll take they work. Thanks.

**Comment by schotime** [comment]
2.4ghz radio is connected using mysensors to nano.
