### ISSUE TITLE
NodeMcu

### ISSUE THREAD

**Issue by dsacristan** [SwiCago/HeatPump#77]
First of all, thank you very much for your project. 

Has somebody tried a NodeMcu(with the ESP8266 and working with 5v)? I wonder if we can use it directly to the CN105, without any tension regulator

thanks

**Comment by SwiCago** [comment]
Only inputs are 5V safe on esp8266, not VIN. Which is 3.3V max... so unless it has onboard regulator, you will kill it. 
The adadfruit huzzah does have a regulator with a pin that can have 5V on it.

**Comment by llemtt** [comment]
I run mine without issues, only an additional mosfet is required at output because esp8266 doesn't support open drain directly (esp32 does).

I think it's not a matter of CN105 but what kind of circuit is connected behind it... I've studied my schematic before doing that way!
