### ISSUE TITLE
Sample circuit: Resistors missing for level adjustment?

### ISSUE THREAD

**Issue by reibuehl** [SwiCago/HeatPump#78]
The sample circuit has two 10K resistors from the ESP pins to 5V. Shouldn't there be matching 20K resistors from the ESP pins to ground to complete the voltage divider for the 5V to 3,3V level shift?

**Comment by SwiCago** [comment]
According to the makers of esp8266 all inputs are 5V safe, so no need for level shifters. Just don't dump full 5V rail into an input! 
BTW: All six of mine are wired exactly like the sample circuit. And have been running non stop for a little over a year now.
