### ISSUE TITLE
Incomplete Mitsubishi Protocol Documentation

### ISSUE THREAD

**Issue by napperley** [SwiCago/HeatPump#81]
The documentation on the [Mitsubishi AirCon protocol](https://github.com/SwiCago/HeatPump/wiki/Mitsubishi-protocol) is **incomplete**. Possible values isn't covered in detail (what does each value mean), no unique name is given for each byte number, the descriptions are too short, and no meaningful examples are provided.

Without complete/meaningful documentation no Software Developer can implement the Mitsubishi AirCon protocol using a programming language ([Kotlin](https://kotlinlang.org/) via [Kotlin Native](https://kotlinlang.org/docs/reference/native-overview.html), Python via [MicroPython](https://micropython.org/) etc).

**Comment by SwiCago** [comment]
Sorry, but this is all voluntary. I had 2 guys said they'd be willing to do documentation, but did not do any. No documentation is not an issue with the library itself! 
**Any good dev worth their weight, can look at the code and figure it out.** That is what I did when I ported this library from python. Don't waste my time with non issues! Closing
