### ISSUE TITLE
onConnectallback() called every 2 seconds

### ISSUE THREAD

**Issue by salas81** [SwiCago/HeatPump#93]
After calling heatpump.connect(&Serial) the onConnectCallback() gets fired every 2 seconds (approximately). Looks like esp is not able to connect

**Comment by SwiCago** [comment]
If it can't connect, then you have a wiring problem. Some esp modules don't work right with the HP. Do you have pull ups? Is your HP a supported model?

**Comment by salas81** [comment]
I have pull-ups, but how do I know if my model is supported?

**Comment by SwiCago** [comment]
https://github.com/SwiCago/HeatPump/wiki/Supported-models

**Comment by SwiCago** [comment]
Hmmm, only thing I can think of is that your wiring may not be good. RX/TX flipped or wires not crimped right.

**Comment by SwiCago** [comment]
@salas81 , have you figured out your problem? It isn't the library. It is doing what it is supposed too. Attempt connect every 2 seconds until successful and send a signal to callback if defined, so the end user can further pass that and be notified of issues. Some guys use that call back to let them know that their HP lost connection.

**Comment by SwiCago** [comment]
Closing. Hit us up in the gitter chat, if you are still having issues with connection
